services:
  frontend:
    build: ./BLOGCRUD
    container_name: ease-blog-react-frontend
    ports:
      - "5173:5173"
    networks:
      - blog_network
  backend:
    build: ./django_backend
    ports:
      - "8000:8000"
    networks:
      - blog_network
  postgres:
    image: postgres:14
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge