FROM python:3.11.0-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project
COPY . /app/

# Migrate database
RUN python manage.py migrate

# Collect static files
#RUN python manage.py collectstatic --noinput

# Create a user to run the application
#RUN python manage.py createsuperuser --noinput

# Run the application
#CMD ["gunicorn", "--bind", "", "backend.wsgi:application"]
